"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

palette = 'amin'

format = """
[╭─](bold noir_1)\
$nix_shell\
$username\
$hostname\
$localip\
$shlvl \
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$direnv\
$env_var\
$custom\
$cmd_duration\
$jobs\
$os\
$container\
$netns\
$shell\
$line_break\
[╰─](bold noir_1)\
$character\
$status\
$sudo"""

[fill]
symbol = ' '

[direnv]
disabled = true

[package]
disabled = true

# left
# ------------------------------------------

[character] 
success_symbol = '[>](bold noir_1)'
error_symbol   = '[>](bold maroon)'

[cmd_duration]
format = ' [ $duration](yellow) '
show_milliseconds = true

[directory]
truncation_symbol = ''
read_only = " "
style = 'bold noir_2'

[git_branch]
format = '[$symbol$branch(:$remote_branch)](bold green dimmed)'

[git_status]
style = 'bold pink dimmed'

[nix_shell]
format = '[ ](bold sapphire)'

[status]
disabled = false
format = '[$status](bold red) '

[sudo]
disabled = false
format = '[ sudo: ](bold maroon)'

# Palette
# ------------------------------------------
[palettes.amin]
rosewater = "#f5e0dc"
flamingo  = "#f2cdcd"
pink      = "#f5c2e7"
mauve     = "#cba6f7"
red       = "#f38ba8"
maroon    = "#eba0ac"
peach     = "#fab387"
yellow    = "#f9e2af"
green     = "#b5f4d6"
teal      = "#94e2d5"
sky       = "#89dceb"
sapphire  = "#74c7ec"
blue      = "#89b4fa"
lavender  = "#b4befe"
cyan      = "#04D7D7"
purple    = "#6B50FF"
text      = "#ffffff"

overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"

surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"

base   = "#1e1e2e"
mantle = "#181825"
crust  = "#11111b"

noir_0 = "#f5f5f5"
noir_1 = "#e8e8e8"
noir_2 = "#9c9c9c"
noir_3 = "#7a7a7a"
noir_4 = "#5f5f5f"
noir_5 = "#494949"
noir_6 = "#353535"
noir_7 = "#252525"
noir_8 = "#1a1a1a"
noir_9 = "#0f0f0f"

# "$schema" = 'https://starship.rs/config-schema.json'
#
# format = """
# [](surface0)\
# $os\
# $username\
# [](bg:peach fg:surface0)\
# $directory\
# [](fg:peach bg:green)\
# $git_branch\
# $git_status\
# [](fg:green bg:teal)\
# $c\
# $rust\
# $golang\
# $nodejs\
# $php\
# $java\
# $kotlin\
# $haskell\
# $python\
# [](fg:teal bg:blue)\
# $docker_context\
# [](fg:blue bg:pink)\
# $time\
# [ ](fg:pink)\
# $line_break$character"""
#
# palette = 'catppuccin_mocha'
#
# [palettes.gruvbox_dark]
# color_fg0 = '#fbf1c7'
# color_bg1 = '#3c3836'
# color_bg3 = '#665c54'
# color_blue = '#458588'
# color_aqua = '#689d6a'
# color_green = '#98971a'
# color_orange = '#d65d0e'
# color_purple = '#b16286'
# color_red = '#cc241d'
# color_yellow = '#d79921'
#
# [palettes.catppuccin_mocha]
# rosewater = "#f5e0dc"
# flamingo = "#f2cdcd"
# pink = "#f5c2e7"
# orange = "#cba6f7"
# red = "#f38ba8"
# maroon = "#eba0ac"
# peach = "#fab387"
# yellow = "#f9e2af"
# green = "#a6e3a1"
# teal = "#94e2d5"
# sky = "#89dceb"
# sapphire = "#74c7ec"
# blue = "#89b4fa"
# lavender = "#b4befe"
# text = "#cdd6f4"
# subtext1 = "#bac2de"
# subtext0 = "#a6adc8"
# overlay2 = "#9399b2"
# overlay1 = "#7f849c"
# overlay0 = "#6c7086"
# surface2 = "#585b70"
# surface1 = "#45475a"
# surface0 = "#313244"
# base = "#1e1e2e"
# mantle = "#181825"
# crust = "#11111b"
#
# [os]
# disabled = false
# style = "bg:surface0 fg:text"
#
# [os.symbols]
# Windows = "󰍲"
# Ubuntu = "󰕈"
# SUSE = ""
# Raspbian = "󰐿"
# Mint = "󰣭"
# Macos = ""
# Manjaro = ""
# Linux = "󰌽"
# Gentoo = "󰣨"
# Fedora = "󰣛"
# Alpine = ""
# Amazon = ""
# Android = ""
# Arch = "󰣇"
# Artix = "󰣇"
# CentOS = ""
# Debian = "󰣚"
# Redhat = "󱄛"
# RedHatEnterprise = "󱄛"
#
# [username]
# show_always = true
# style_user = "bg:surface0 fg:text"
# style_root = "bg:surface0 fg:text"
# format = '[ $user ]($style)'
#
# [directory]
# style = "fg:mantle bg:peach"
# format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "…/"
#
# [directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = "󰝚 "
# "Pictures" = " "
# "Developer" = "󰲋 "
#
# [git_branch]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol $branch ](fg:base bg:green)]($style)'
#
# [git_status]
# style = "bg:teal"
# format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'
#
# [nodejs]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [c]
# symbol = " "
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [rust]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [golang]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [php]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [java]
# symbol = " "
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [kotlin]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [haskell]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [python]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [docker_context]
# symbol = ""
# style = "bg:mantle"
# format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'
#
# [time]
# disabled = false
# time_format = "%R"
# style = "bg:peach"
# format = '[[  $time ](fg:mantle bg:pink)]($style)'
#
# [line_break]
# disabled = false
#
# [character]
# disabled = false
# success_symbol = '[](bold fg:green)'
# error_symbol = '[](bold fg:red)'
# vimcmd_symbol = '[](bold fg:creen)'
# vimcmd_replace_one_symbol = '[](bold fg:purple)'
# vimcmd_replace_symbol = '[](bold fg:purple)'
# vimcmd_visual_symbol = '[](bold fg:lavender)'
#
